In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("/Users/soumobratamanna/Documents/AI_ML PROJECTS/Heart_Disease_Prediction.csv")

In [3]:
data.shape

(270, 14)

In [4]:
data.head(10)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
5,65,1,4,120,177,0,0,140,0,0.4,1,0,7,Absence
6,56,1,3,130,256,1,2,142,1,0.6,2,1,6,Presence
7,59,1,4,110,239,0,2,142,1,1.2,2,1,7,Presence
8,60,1,4,140,293,0,2,170,0,1.2,2,2,7,Presence
9,63,0,4,150,407,0,2,154,0,4.0,2,3,7,Presence

In [5]:
data.tail(10)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
260,58,0,3,120,340,0,0,172,0,0.0,1,0,3,Absence
261,60,1,4,130,206,0,2,132,1,2.4,2,2,7,Presence
262,58,1,2,120,284,0,2,160,0,1.8,2,0,3,Presence
263,49,1,2,130,266,0,0,171,0,0.6,1,0,3,Absence
264,48,1,2,110,229,0,0,168,0,1.0,3,0,7,Presence
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [6]:
data.info

<bound method DataFrame.info of      Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0     70    1                4  130          322             0            2
1     67    0                3  115          564             0            2
2     57    1                2  124          261             0            0
3     64    1                4  128          263             0            0
4     74    0                2  120          269             0            2
..   ...  ...              ...  ...          ...           ...          ...
265   52    1                3  172          199             1            0
266   44    1                2  120          263             0            0
267   56    0                2  140          294             0            2
268   57    1                4  140          192             0            0
269   67    1                4  160          286             0            2

     Max HR  Exercise angina  ST depression  Slope of ST  \
0       109                0            2.4            2
1       160                0            1.6            2
2       141                0            0.3            1
3       105                1            0.2            2
4       121                1            0.2            1
..      ...              ...            ...          ...
265     162                0            0.5            1
266     173                0            0.0            1
267     153                0            1.3            2
268     148                0            0.4            2
269     108                1            1.5            2

     Number of vessels fluro  Thallium Heart Disease
0                          3         3      Presence
1                          0         7       Absence
2                          0         7      Presence
3                          1         7       Absence
4                          1         3       Absence
..                       ...       ...           ...
265                        0         7       Absence
266                        0         7       Absence
267                        0         3       Absence
268                        0         6       Absence
269                        3         3      Presence

[270 rows x 14 columns]>

In [7]:
data.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [8]:
#Encoding Presence  and Absence into 1 and 0
data['Heart Disease'] = data['Heart Disease'].map({'Presence':1,'Absence':0})

In [9]:
data['Heart Disease'].unique()

array([1, 0])

In [10]:
data.head(10)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,1
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,0
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,1
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,0
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,0
5,65,1,4,120,177,0,0,140,0,0.4,1,0,7,0
6,56,1,3,130,256,1,2,142,1,0.6,2,1,6,1
7,59,1,4,110,239,0,2,142,1,1.2,2,1,7,1
8,60,1,4,140,293,0,2,170,0,1.2,2,2,7,1
9,63,0,4,150,407,0,2,154,0,4.0,2,3,7,1

In [11]:
data.describe()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
count,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000,270.000000,270.000000,270.000000
mean,54.433333,0.677778,3.174074,131.344444,249.659259,0.148148,1.022222,149.677778,0.329630,1.05000,1.585185,0.670370,4.696296,0.444444
std,9.109067,0.468195,0.950090,17.861608,51.686237,0.355906,0.997891,23.165717,0.470952,1.14521,0.614390,0.943896,1.940659,0.497827
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.00000,1.000000,0.000000,3.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,213.000000,0.000000,0.000000,133.000000,0.000000,0.00000,1.000000,0.000000,3.000000,0.000000
50%,55.000000,1.000000,3.000000,130.000000,245.000000,0.000000,2.000000,153.500000,0.000000,0.80000,2.000000,0.000000,3.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,280.000000,0.000000,2.000000,166.000000,1.000000,1.60000,2.000000,1.000000,7.000000,1.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.20000,3.000000,3.000000,7.000000,1.000000

In [12]:
#checking the number of PAtients having heart diseases 
data['Heart Disease'].value_counts()

0    150
1    120
Name: Heart Disease, dtype: int64

In [14]:
#Splitting the datas between independent and dependent variable of X and Y
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [15]:
X

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3

In [16]:
Y

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: Heart Disease, Length: 270, dtype: int64

In [17]:
#Dividing data between training and testing data
#stratify = y is used to divide the the columns of Y evenly 
X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify = Y,random_state=2)

In [18]:
X.shape

(270, 13)

In [19]:
Y.shape

(270,)

In [20]:
X_train

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
101,67,1,4,120,237,0,0,71,0,1.0,2,0,3
16,46,1,4,140,311,0,0,120,1,1.8,2,2,7
108,59,1,4,140,177,0,0,162,1,0.0,1,1,7
262,58,1,2,120,284,0,2,160,0,1.8,2,0,3
244,51,0,3,140,308,0,2,142,0,1.5,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,52,1,2,128,205,1,0,184,0,0.0,1,0,3
32,37,0,3,120,215,0,0,170,0,0.0,1,0,3
33,59,1,4,170,326,0,2,140,1,3.4,3,0,7
13,61,1,1,134,234,0,0,145,0,2.6,2,2,3
24,54,0,2,132,288,1,2,159,1,0.0,1,1,3

In [23]:
X_test

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
213,58,1,4,128,216,0,2,131,1,2.2,2,3,7
264,48,1,2,110,229,0,0,168,0,1.0,3,0,7
211,51,1,3,125,245,1,2,166,0,2.4,2,0,3
76,45,1,4,104,208,0,2,148,1,3.0,2,0,3
187,52,1,4,108,233,1,0,147,0,0.1,1,3,7
125,54,0,3,160,201,0,0,163,0,0.0,1,1,3
40,40,1,4,152,223,0,0,181,0,0.0,1,0,7
248,60,1,3,140,185,0,2,155,0,3.0,2,0,3
60,57,1,3,150,126,1,0,173,0,0.2,1,1,7
93,54,1,4,110,206,0,2,108,1,0.0,2,1,3
114,42,1,2,120,295,0,0,162,0,0.0,1,0,3
55,41,0,2,105,198,0,0,168,0,0.0,1,1,3
49,65,0,4,150,225,0,2,114,0,1.0,2,3,7
128,52,1,2,134,201,0,0,158,0,0.8,1,1,3
104,63,1,4,130,254,0,2,147,0,1.4,2,1,7
127,52,0,3,136,196,0,2,169,0,0.1,2,0,3
122,57,1,4,152,274,0,0,88,1,1.2,2,1,7
202,60,1,4,125,258,0,2,141,1,2.8,2,1,7
25,48,0,3,130,275,0,0,139,0,0.2,1,0,3
91,61,0,4,130,330,0,2,169,0,0.0,1,0,3
138,34,0,2,118,210,0,0,192,0,0.7,1,0,3
116,46,1,4,120,249,0,2,144,0,0.8,1,0,7
134,54,1,3,150,232,0,2,165,0,1.6,1,0,7
83,41,1,3,130,214,0,2,168,0,2.0,2,0,3
79,56,1,2,120,236,0,0,178,0,0.8,1,0,3
10,59,1,4,135,234,0,0,161,0,0.5,2,0,7
46,49,1,3,118,149,0,2,126,0,0.8,1,3,3
68,44,0,3,118,242,0,0,149,0,0.3,2,1,3
190,54,1,4,140,239,0,0,160,0,1.2,1,0,3
263,49,1,2,130,266,0,0,171,0,0.6,1,0,3
48,66,1,2,160,246,0,0,120,1,0.0,2,3,6
195,55,0,2,135,250,0,2,161,0,1.4,2,0,3
124,54,1,3,125,273,0,2,152,0,0.5,3,1,3
231,39,1,4,118,219,0,0,140,0,1.2,2,0,7
20,67,1,4,120,229,0,2,129,1,2.6,2,2,7
182,41,1,4,110,172,0,2,158,0,0.0,1,0,7
247,65,0,3,155,269,0,0,148,0,0.8,1,0,3
39,48,1,4,122,222,0,2,186,0,0.0,1,0,3
17,53,1,4,140,203,1,2,155,1,3.1,3,0,7
87,59,1,1,178,270,0,2,145,0,4.2,3,0,7
222,57,1,3,150,168,0,0,174,0,1.6,1,0,3
66,51,1,4,140,261,0,2,186,1,0.0,1,0,3
175,62,0,4,138,294,1,0,106,0,1.9,2,3,3
102,49,0,4,130,269,0,0,163,0,0.0,1,0,3
94,52,1,4,125,212,0,0,168,0,1.0,1,2,7
235,62,0,4,160,164,0,2,145,0,6.2,3,3,7
110,55,0,4,180,327,0,1,117,1,3.4,2,0,3
89,50,1,4,150,243,0,2,128,0,2.6,2,0,7
173,68,0,3,120,211,0,2,115,0,1.5,2,0,3
14,57,0,4,128,303,0,2,159,0,0.0,1,1,3
160,38,1,1,120,231,0,0,182,1,3.8,2,0,7
233,52,1,4,128,255,0,0,161,1,0.0,1,1,7
188,62,0,4,140,394,0,2,157,0,1.2,2,0,3
162,55,1,2,130,262,0,0,155,0,0.0,1,0,3

In [22]:
#Training the mdoel

In [24]:
model = LogisticRegression()

In [25]:
model.fit(X_train,Y_train)

/opt/homebrew/Cellar/jupyterlab/3.3.2/libexec/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [28]:
#Evaluation metrics

In [29]:
#Checking the accuracy score of the training dataset

In [30]:
X_train_predictions = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_predictions,Y_train)

In [31]:
training_data_accuracy

0.875

In [32]:
#Checking the accuracy score of the testing dataset

In [33]:
X_test_predictions = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_predictions,Y_test)

In [34]:
testing_data_accuracy

0.8333333333333334

In [35]:
#Imp Note - If the accuracy score of training data is way too large and the accuracy score of testing data is way too small then the model is overfitted
#The accuracy score between training and testing data should be near about or almost similar or close to each other .

In [40]:
# BUILDING A PREDICTIVE SYSTEM - 1 means heart disease present and 0 means not present

In [51]:
input_data = (70,1,4,130,322,0,2,109,0,2.4,2,3,3)

#changing to numpy array beacuse we have to reshape it and its easy to reshape numpy array than a tuples 
input_data_as_numpy_array = np.asarray(input_data)

#Reshaping because we need to predict the value of 1 data row
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

predictions = model.predict(input_data_reshaped)

print(predictions)

if(predictions[0] == 0):
    print("The person is healthy heart disease : result negative")
else:
    print("The person is not healthy heart disease : result positive")

[1]
The person is not healthy heart disease : result positive

/opt/homebrew/Cellar/jupyterlab/3.3.2/libexec/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [52]:
input_data = (67,0,3,115,564,0,2,160,0,1.6,2,0,7)

#changing to numpy array beacuse we have to reshape it and its easy to reshape numpy array than a tuples 
input_data_as_numpy_array = np.asarray(input_data)

#Reshaping because we need to predict the value of 1 data row
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

predictions = model.predict(input_data_reshaped)

print(predictions)

if(predictions[0] == 0):
    print("The person is healthy heart disease : result negative")
else:
    print("The person is not healthy heart disease : result positive")

[0]
The person is healthy heart disease : result negative

/opt/homebrew/Cellar/jupyterlab/3.3.2/libexec/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(